### ISSUE TITLE
Issue 0001; Branch: UnstableChanges. Title: Crashing When Pressing Enter

### ISSUE THREAD

**Issue by mahyargorji** [UglyShirtTrio/SummerSunSet#1]
Branch: UnstableChanges

The app takes input in input-fields from the user, but crashes when pressing enter. 
Through some code analysis, I removed errors that were being caused by XML field android:textAlignment, but the app seems to not tell us why it crashes. 

All members, please investigate.

**Comment by Parastoo-S** [comment]
Fixed the issue:)
